<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerACOtYrj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerACOtYrj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerACOtYrj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerACOtYrj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerACOtYrj\App_KernelDevDebugContainer([
    'container.build_hash' => 'ACOtYrj',
    'container.build_id' => 'f779b5c5',
    'container.build_time' => 1744745169,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerACOtYrj');
